import os
os.system('python run.py --project_name Chart --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Cli --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Codec --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Collections --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Compress --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Csv --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Gson --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name JacksonCore --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
# os.system('python run.py --project_name JacksonDatabind --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name JacksonXml --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Jsoup --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name JxPath --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
# os.system('python run.py --project_name Lang --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
# os.system('python run.py --project_name Math --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Mockito --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
# os.system('python run.py --project_name Time --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Chart --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Cli --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Codec --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Collections --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Compress --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Csv --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Gson --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name JacksonCore --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
# os.system('python run.py --project_name JacksonDatabind --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name JacksonXml --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Jsoup --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name JxPath --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
# os.system('python run.py --project_name Lang --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
# os.system('python run.py --project_name Math --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Mockito --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
# os.system('python run.py --project_name Time --model_name codebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Chart --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Cli --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Codec --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Collections --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Compress --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Csv --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Gson --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name JacksonCore --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
# os.system('python run.py --project_name JacksonDatabind --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name JacksonXml --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Jsoup --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name JxPath --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
# os.system('python run.py --project_name Lang --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
# os.system('python run.py --project_name Math --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Mockito --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
# os.system('python run.py --project_name Time --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Chart --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Cli --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Codec --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Collections --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Compress --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Csv --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Gson --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name JacksonCore --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
# os.system('python run.py --project_name JacksonDatabind --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name JacksonXml --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Jsoup --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name JxPath --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
# os.system('python run.py --project_name Lang --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
# os.system('python run.py --project_name Math --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Mockito --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
# os.system('python run.py --project_name Time --model_name graphcodebert --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Chart --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Cli --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Codec --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Collections --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Compress --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Csv --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Gson --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name JacksonCore --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
# os.system('python run.py --project_name JacksonDatabind --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name JacksonXml --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Jsoup --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name JxPath --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
# os.system('python run.py --project_name Lang --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
# os.system('python run.py --project_name Math --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Mockito --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
# os.system('python run.py --project_name Time --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name cosine --repeat 50')
os.system('python run.py --project_name Chart --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Cli --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Codec --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Collections --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Compress --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Csv --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Gson --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name JacksonCore --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
# os.system('python run.py --project_name JacksonDatabind --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name JacksonXml --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Jsoup --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name JxPath --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
# os.system('python run.py --project_name Lang --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
# os.system('python run.py --project_name Math --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
os.system('python run.py --project_name Mockito --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')
# os.system('python run.py --project_name Time --model_name unixcoder --calculate_apfd --save_sim_matrix --calculate_similarity --sim_name euclidean --repeat 50')